version: "3.9"

services:
  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - target: 5432
        published: 29175
        protocol: tcp
        mode: host

  webapp:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: .
    image: booking/booking-service
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - target: $SERVER_PORT
        published: 9001
        protocol: tcp
        mode: host
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 3
